### ISSUE TITLE
Scroll bar in Navigation when changing tabs

### ISSUE THREAD

**Issue by tglass1976** [mattcoker/dtns-archive#2]
Minor issue in the navigation bar. When the page is freshly loaded and you switch to another page, a scroll bar briefly appears in the navigation bar. This only seems to happen when the page is first loaded. I can recreate it by refreshing the page and navigating again, but a second attempt without a refresh works fine.

This does not prevent usage of the site, it only appears for a second or two while the new page is loading. Replicated on Chrome and Opera.

Attaching a screenshot.
![2017-02-15 14_16_25-episodes - daily tech news show archives](https://cloud.githubusercontent.com/assets/25388693/22991222/a00295ee-f389-11e6-83cf-1284c286db9d.png)

**Comment by mattcoker** [comment]
@tglass1976 So far I have been unable to replicate this. It looks like you're browsing on some version of Windows, is that correct? Can you tell provide some OS/Browser version numbers for me to test with?

Also, you say it occurs when switching to another page. Do you mean within the application, or do you mean to an external URL?

**Comment by tglass1976** [comment]
OS: Windows 10 Pro, Version 1607, Build 14393.693 64-bit
Browser: Chrome Version 56.0.2924.87
Also saw this on Opera Version:	43.0.2442.806 (PGO)

By switching to another page, I mean clicking on another tab in the navigation bar for the site such as Episodes or Picks. Only happens after a fresh load of the site, so you can hit the refresh button in the browser then click on a tab and you should see it happen for a second. It happens quick, I took the screenshot quickly and managed to capture it.

**Comment by tglass1976** [comment]
FYI, I'm not seeing this behavior now after you made changes to how the site loads.

**Comment by mattcoker** [comment]
@tglass1976 Are you referring to the implementation of Fastboot, which enabled server-side rendering? That seemed to have decreased the time-to-render from about 15 seconds to ~5, though I can't imagine why that would solve what appears to be a CSS cross-browser-compatibility issue.

**Comment by tglass1976** [comment]
@mattcoker Correct. Could be coincidence but I have not been able to reproduce since then.

**Comment by mattcoker** [comment]
In that case, we'll keep this open for a bit and see if the issue crops up again.
